#!/bin/sh

set -eo pipefail

uv run isort --check --quiet --profile black mapdeduce test

uv run black --check mapdeduce test

uv run flake8 mapdeduce test

uv run pytest --no-header --no-summary --quiet
